/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pleasedonut.gltf --transform 
Files: pleasedonut.gltf [5.05KB] > /Users/hrkim/Documents/Study/new-portfolio/portfolio/public/pleasedonut-transformed.glb [243.12KB] (-4714%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pleasedonut-transformed.glb')
  const settedColor = new THREE.MeshLambertMaterial({ color: "red" })
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.donut002.geometry} material={materials['Material.003']} position={[-0.259, 0.017, -0.029]} />
      <mesh geometry={nodes.icing002.geometry} material={materials['Material.002']} position={[-0.259, 0.017, -0.029]} />
      {/* <mesh geometry={nodes.icing003.geometry} material={materials['Material.005']} position={[-0.259, 0.017, -0.029]} /> */}
      <mesh geometry={nodes.icing003.geometry} material={settedColor} position={[-0.259, 0.017, -0.029]} />
    </group>
  )
}

useGLTF.preload('/pleasedonut-transformed.glb')
