/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pleasedonut.gltf --transform 
Files: pleasedonut.gltf [5.05KB] > /Users/hrkim/Documents/Study/new-portfolio/portfolio/public/pleasedonut-transformed.glb [243.12KB] (-4714%)
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { useSnapshot } from "valtio";

export default function PleaseDonut({ state, onColorChange }) {
  const { nodes, materials } = useGLTF("/pleasedonut-transformed.glb");
  const ref = useRef();
  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    ref.current.rotation.set(
      Math.cos(t / 4) / 4,
      Math.sin(t / 4) / 4,
      -0.2 - (1 + Math.sin(t / 1.5)) / 20
    );
    ref.current.position.y = (1 + Math.sin(t / 1.5)) / 80;
  });
  const snap = useSnapshot(state);
  materials["Material.002"].color.set(snap.color);
  function handleClick(e) {
    e.stopPropagation();
    state.offsetX = e.offsetX;
    state.offsetY = e.offsetY;
    state.current = "click";
    onColorChange();
  }
  
  const cursorSvg = '<svg xmlns="http://www.w3.org/2000/svg" width="77" height="77" viewBox="0 0 100 100" fill="none"><text x="30" y="15" fill="black" font-family="Montserrat, sans-serif">CLICK!</text><rect width="27" height="27" rx="38.5" fill="black"/></svg>'
  
  return (
    <group ref={ref}>
      <mesh
        geometry={nodes.donut002.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        geometry={nodes.icing002.geometry}
        material={materials["Material.002"]}
        onClick={handleClick}
        onPointerMissed={() => (state.current = null)}
        onPointerOver={() => (document.body.style.cursor = `url("data:image/svg+xml;base64,${btoa(cursorSvg)}"), pointer`)}
        onPointerOut={() => (document.body.style.cursor = "")}
      />
      <mesh
        geometry={nodes.icing003.geometry}
        material={materials["Material.005"]}
      />
    </group>
  );
}

useGLTF.preload("/pleasedonut-transformed.glb");
